---
title: "Research Projects"
---

### Recently completed

1️⃣: Azam, J.M., Pang, X., Are, E.B., Pulliam, J.R. and Ferrari, M.J., 2023. [Modelling outbreak response impact in human vaccine-preventable diseases: A systematic review of differences in practices between collaboration types before COVID-19](https://doi.org/10.1016/j.epidem.2023.100720). Epidemics, p.100720.

### Ongoing work

1️⃣: [Age-structured compartmental model](https://github.com/SACEMA/sa-polio-model) for 
estimating the timing of detection of polio-related acute flaccid paralysis in South 
Africa (generalizable to other settings).
    
2️⃣: [A surveillance pipeline](https://github.com/SACEMA/severity-monitoring) to detect 
changes in reported COVID-19 severity (case fatality, case hospitalization, and 
hospital fatality).
    
3️⃣: [A two-strain compartmental model](https://github.com/jamesmbaazam/two_strain_orv_model) 
for studying the impact of the timing of the emergence of variants on control strategies.

### Broad research interests

1️⃣: Compartmental modelling of the impact of control measures against infectious diseases. 

2️⃣: (Bayesian) Models and methods for (near) real-time forecasting and nowcasting of infectious diseases. 

Find out more from my [Google Scholar profile](https://scholar.google.co.za/citations?user=IxRpXp8AAAAJ&hl=en).

